### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by sabas** [miwurster/atom-github-theme#1]
Latest Atom has 4 warnings from your theme, mostly related to less variables which have been deprecated..

**Comment by miwurster** [comment]
Thanks! Will look into it tomorrow...

Cheers,
Michael

**Comment by miwurster** [comment]
@sabas I made some adaptions to meet the new 1.0 API and published a new version (v0.2.0).
Could you please also verify that everything is working as expected? 

Thanks,
Michael

**Comment by sabas** [comment]
Yep it don't give the warnings anymore! Thanks!

**Comment by miwurster** [comment]
Thanks for verifying...
